title: Franck DEFFO | Cybersécurité & Infrastructures SI
description: Portfolio d'ingénierie en cybersécurité, infrastructures SI et AMOA.
baseurl: /Franck-DEFFO-.github.io
url: https://franck922.github.io
